name: NPM Build Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Started NPM Build Job"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Checking NodeJs & NPM Versions
        run: |
          echo "Node Version check"
          node -v
          echo "NPM Version check"
          npm -v
      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps
          npm install -g @angular/cli
      - name: Build for prod
        run: |
          npm run build
      - name: Upload dist folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: ./dist
  deploy-ghpages:
    runs-on: ubuntu-latest
    needs: npm-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Checkout repository in the deployment job
      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages
      - name: Download ./dist/browser folder from previous job
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist/browser
      - name: Set up Git for deployment
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Deploy to Github Pages
        run: angular-cli-ghpages -d ./browser/ --repo="https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/vukkumsp/polling-booth.git" --no-silent